server:
  port: 11000

# jdbc_config   datasource
datasource:
  db:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/dianwanjia_official_website?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456

spring.application.name: pro.dianwanjia.official.website

logging:
    level:
        pro.dianwanjia.official.website: DEBUG



