server:
  port: 11000

# jdbc_config   datasource
datasource:
  db:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/dianwanjia_official_website?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    jdbc-url: jdbc:mysql://localhost:3306/dianwanjia?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
#    username: root
#    password: 123456
## Hikari will use the above plus the following to setup connection pooling
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      minimum-idle: 5
#      maximum-pool-size: 15
#      auto-commit: true
#      idle-timeout: 30000
#      pool-name: DatebookHikariCP
#      max-lifetime: 1800000
#      connection-timeout: 30000
#      connection-test-query: SELECT 1

#mybatis:
#  mapper-locations: classpath:mybatis-mapper/*.xml

spring.application.name: pro.dianwanjia.official.website

#sql日志打印
logging:
  level:
    com.lx.oneSentence.mapper: DEBUG


